apiVersion: v1
kind: Deployment
metadata:
  name: my-api
  labels:
    name: my-api
spec:
  selector:
    matchLabels:
      name: my-api
  replicas: 2
  template:
    metadata:
      labels:
        name: my-api
    spec:
      containers:
        - name: my-api
          image: my-image
          envFrom:
            - configMapRef:
                name: myapp-env
            - secretRef:
                name: myapp-secret
                
          volumeMounts:
            - mountPath: "/go/family"
              name: myvolume
              readOnly: true

      volumes:
        - name: myvolume
          configMap:
            name: myapp-family..
            items:
            - key: members
              path: "family.txt"