microservice:
  name: grade-submission-api
  namespace: grade-submission
  replicas: 2
  
workload:
  image: rslim087/kubernetes-course-grade-submission-api:stateless-v4
  port: 3000
  resources:
    memory: "128mi"
    cpu: "128mi"
  livenessDelay: 15

secrets:
  MONGODB_URI: 'mongodb://user:password123@mongodb-grade-submission-svc.mongodb.svc.cluster.local:27017/grades'