apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  type: ClusterIP #Access to node via local
  selector:
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  ports:
  - port: {{ .Values.workload.port }}
    targetPort: {{ .Values.workload.port }}

#kubectl apply -f grade-submission-portal-pod.yaml
#kubectl apply -f grade-submission-portal-service.yaml