apiVersion: v1
kind: Service
metadata:
  name: grade-submission-portal
  namespace: grade-submission
spec:
  type: NodePort #Access to node via local
  selector:
    app.kubernetes.io/instance: grade-submission-portal
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 32000 #30000 to 32000

#kubectl apply -f grade-submission-portal-pod.yaml
#kubectl apply -f grade-submission-portal-service.yaml