apiVersion: v1
kind: Pod
metadata:
  name: my-api
  labels:
    name: my-api
spec:
  containers:
  - name: my-api
    image: my-image
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: <Port>
