apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-api
  labels:
    name: my-api
spec:
  selector:
    matchLabels:
      name: my-api
  replicas: 2
  template:
    metadata:
      labels:
        name: my-api
    spec:
      containers:
      - name: my-api
        image: my-image