apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
spec:  
  selector:
    app.kubernetes.io/instance: grade-submission-api
  ports:
  - port: 3000 #service port
    targetPort: 3000 #target pod port/container