apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:  
#type is clusterIp to internal communication inside the cluster
  selector:
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  ports:
  - port: {{ .Values.workload.port }} #service port
    targetPort: {{ .Values.workload.port }} #target pod port/container

#kubectl apply -f grade-submission-portal-pod.yaml
#kubectl apply -f grade-submission-portal-service.yaml